name: ESLint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'

      - name: Cache Node
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Node
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install
      
      - name: eslint
        run: yarn run eslint .